name: Create Release
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release:
    name: Create Release
    needs: [build-artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Compress artifacts
        run: tar -czvf artifacts.tar.gz artifacts

      - name: Publish To Dedicated Repo
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TO }}
        run: |
          gh release create ${{github.ref_name}}  artifacts.tar.gz -R https://github.com/pigfall/release-to-other-repo-to-demo/
          
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: program.sh
          path: program.sh
          retention-days: 1
